Drobnosti/ComTrans/src/java/com/bistudio/ComTrans/SessionBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bistudio.ComTrans;

import com.unboundid.ldap.sdk.BindResult;
import com.unboundid.ldap.sdk.LDAPConnection;
import com.unboundid.ldap.sdk.LDAPConnectionOptions;
import com.unboundid.ldap.sdk.LDAPException;
import com.unboundid.ldap.sdk.ResultCode;
import com.unboundid.ldap.sdk.SearchResult;
import com.unboundid.ldap.sdk.SearchScope;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collection;
import java.util.logging.Logger;
import javax.faces.application.Application;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.el.ValueBinding;
import javax.faces.model.DataModel;
import javax.net.ssl.SSLSocketFactory;

/**
 *
 * @author Jirka
 */
@ManagedBean(name = "sessionBean")
@SessionScoped
public class SessionBean 
{
    // Login properties
    private String name;
    public String getName() {return name;}
    public void setName(String value) {name = value;}

    private String password;
    public String getPassword() {return password;}
    public void setPassword(String value) {password = value;}

    private String errorMsg;
    public String getErrorMsg() {return errorMsg;}
    public void setErrorMsg(String value) {errorMsg = value;}
    
    public String login()
    {
        LDAPConnectionOptions ops = new LDAPConnectionOptions();
        ops.setAutoReconnect(true);
        ops.setBindWithDNRequiresPassword(true);
        ops.setResponseTimeoutMillis(0);
        ops.setUseKeepAlive(true);
        ops.setUseTCPNoDelay(true);

        ApplicationBean app = getApplicationBean();
        SSLSocketFactory socketFactory = app.getSocketFactory();

        String host = app.getLdapHost();
        int port = app.getLdapPort();
        String userMask = app.getLdapUserMask();
        String groupDN = app.getLdapGroupDN();
        String userDN = String.format(userMask, name);

        try
        {
            LDAPConnection c = new LDAPConnection(socketFactory, ops);
            c.connect(host, port);
            BindResult ok = c.bind(userDN, password);
            if (ok.getResultCode() != ResultCode.SUCCESS)
            {
                errorMsg = "Login failed, wrong name or password";
                return "fail";
            }
            
            SearchResult isInGroup = c.search(groupDN, SearchScope.SUB,
                    "(member=" + userDN + ")", "member");

            if (isInGroup.getEntryCount() == 0)
            {
                errorMsg = "Login failed, no access rights";
                return "fail";
            }
            
            return "ok";
        }
        catch (LDAPException ex)
        {
            errorMsg = ex.getMessage();
            return "fail";
        }
    }

    // Main form properties

    public class Language
    {
        private int id;
        public int getId() {return id;}
        public void setId(int value) {id = value;}

        private String name;
        public String getName() {return name;}
        public void setName(String value) {name = value;}
        
        public Language(int id, String name)
        {
            this.id = id; this.name = name;
        }
    }
    private ArrayList<Language> languages = new ArrayList<Language>();
    public ArrayList<Language> getLanguages() {return languages;}
    public void setLanguages(ArrayList<Language> value) {languages = value;}
    private void loadLanguages()
    {
        languages.clear();
        
        ApplicationBean app = getApplicationBean();
        Connection connection = null;
        try
        {
            connection = app.openConnection();

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT LanguageID, Name FROM Languages");
            while (resultSet.next())
            {
                languages.add(new Language(resultSet.getInt(1), resultSet.getString(2)));
            }
            resultSet.close();
            statement.close();
        }
        catch (Exception exception)
        {
            Logger.getGlobal().severe(exception.toString());
        }
        finally
        {
            app.closeConnection(connection);
        }
    }

    // Left panel

    private Integer translateToCurrent = null;
    public Integer getTranslateToCurrent() {return translateToCurrent;}
    public void setTranslateToCurrent(Integer value) {translateToCurrent = value;}
    public void onTranslateToSelected()
    {
        // if selection did not change, update only translation (different language)
        if (!loadStrings(null))
            updateTranslation();
    }
    
    private Boolean showTranslated;
    public Boolean getShowTranslated() {return showTranslated;}
    public final void setShowTranslated(Boolean value) {showTranslated = value;}
    public void onShowTranslatedChanged()
    {
        loadStrings(null);
    }

    public class Project
    {
        private int id;
        public int getId() {return id;}
        public void setId(int value) {id = value;}

        private String name;
        public String getName() {return name;}
        public void setName(String value) {name = value;}
        
        public Project(int id, String name)
        {
            this.id = id; this.name = name;
        }
    }
    private ArrayList<Project> projects = new ArrayList<Project>();
    public ArrayList<Project> getProjects() {return projects;}
    public void setProjects(ArrayList<Project> value) {projects = value;}
    private Integer projectsCurrent = null;
    public Integer getProjectsCurrent() {return projectsCurrent;}
    public void setProjectsCurrent(Integer value) {projectsCurrent = value;}
    public void onProjectSelected()
    {
        loadStrings(null);
    }
    private final void loadProjects()
    {
        projects.clear();
        
        ApplicationBean app = getApplicationBean();
        Connection connection = null;
        try
        {
            connection = app.openConnection();

            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT ProjectID, Name FROM Projects");
            while (resultSet.next())
            {
                projects.add(new Project(resultSet.getInt(1), resultSet.getString(2)));
            }
            resultSet.close();
            statement.close();
        }
        catch (Exception exception)
        {
            Logger.getGlobal().severe(exception.toString());
        }
        finally
        {
            app.closeConnection(connection);
        }
    }
    
    public class Strings extends DataModel<Strings.Item>
    {
        public class Item
        {
            private int id;
            public int getId() {return id;}
            public void setId(int value) {id = value;}
            
            private String text;
            public String getText() {return text;}
            public void setText(String value) {text = value;}

            public Item(int id, String text)
            {
                this.id = id;
                this.text = text;
            }
        }
        private ArrayList<Item> items = new ArrayList<Item>();

        private void clear()
        {
            items.clear();
        }
        private void add(int id, String text)
        {
            items.add(new Item(id, text));
        }
        private int findIndex(Integer id) 
        {
            for (int i=0; i<items.size(); i++)
            {
                if (items.get(i).id == id) return i;
            }
            return -1;
        }

        // DataModel implementation
        private int _currentRow = -1;
        @Override
        public boolean isRowAvailable() 
        {
            return _currentRow >= 0 && _currentRow < items.size();
        }
        @Override
        public int getRowCount() 
        {
            return items.size();
        }
        @Override
        public Item getRowData() 
        {
            if (_currentRow < 0) return null;
            return items.get(_currentRow);
        }
        @Override
        public int getRowIndex() 
        {
            return _currentRow;
        }
        @Override
        public void setRowIndex(int rowIndex) 
        {
            _currentRow = rowIndex;
        }
        @Override
        public Object getWrappedData() 
        {
            return null;
        }
        @Override
        public void setWrappedData(Object data) 
        {
        }
    }
    private Strings strings = new Strings();
    public Strings getStrings() {return strings;}

    private Collection<Object> _selection = null;
    public Collection<Object> getStringsCurrent() {return _selection;}
    public final void setStringsCurrent(Collection<Object> value) {_selection = value;}
    public Integer getSelectedString()
    {
        if (_selection == null) return null;
        
        for (Object obj : _selection)
        {
            Integer index = (Integer)obj;
            Strings.Item item = strings.items.get(index);
            return item.id;
        }
        return null;
    }

    private final boolean loadStrings(Integer select)
    {
        Integer selectedBefore = getSelectedString();
        if (select == null) select = selectedBefore;
        
        // read from database
        strings.clear();
        
        if (projectsCurrent != null)
        {
            ApplicationBean app = getApplicationBean();
            Connection connection = null;
            try
            {
                connection = app.openConnection();

                PreparedStatement statement = null;
                if (showTranslated != null && showTranslated)
                {

Drobnosti/ComTrans/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Community Translator Login</title>
    </h:head>
    <h:body>
        <center>
        <h:panelGrid width="20%">
            <rich:panel>
                <f:facet name="header">
                    <h:outputText value="Community Translator Login" />
                </f:facet>
                <h:form>
                    <h:panelGrid columns="2">
                        <h:outputText value="Login name:" /> 
                        <h:inputText id="name" value="#{sessionBean.name}" styleClass="inputbox" autocomplete="true"/>
                        <h:outputText value=""/>
                        <h:message for="name" styleClass="errors"/>
                        <h:outputText value="Password:" /> 
                        <h:inputSecret id="password" value="#{sessionBean.password}" styleClass="inputbox" autocomplete="true"/>
                        <h:outputText value=""/>
                        <h:message for="password" styleClass="errors"/>
                    </h:panelGrid>
                    <center>
                        <h:commandButton value="Login" action="#{sessionBean.login}" styleClass="submitButton"/>
                    </center>
                </h:form>
            </rich:panel>
        </h:panelGrid>
        </center>
    </h:body>
</html>

Drobnosti/ComTrans/web/loginFailed.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Community Translator</title>
    </h:head>
    <h:body>
        <center>
            <rich:panel>
                <f:facet name="header">
                    <h:outputText value="Login Failed" />
                </f:facet>
                <h:form>
                    <center>
                        <h:outputText value="#{sessionBean.errorMsg}" />
                        <h:commandButton value="Back" action="back" styleClass="submitButton"/>
                    </center>
                </h:form>
            </rich:panel>
        </center>
    </h:body>
</html>

Drobnosti/ComTrans/web/translator.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Community Translator</title>
        <style type="text/css">
            *{padding:0; margin:0}
            html, body {height:100%}
        </style>
    </h:head>
    <h:body>
        <h:form prependId="false">
            <h:panelGrid columns="2">
                <rich:panel style="width:400px; height:600px" id="left">
                    <br/>
                    <h:outputText value="Translate to: "/>
                    <rich:select id="translateTo" value="#{sessionBean.translateToCurrent}">
                         <a4j:ajax execute="@this" event="selectitem"
                                   listener="#{sessionBean.onTranslateToSelected}" render="@form"/>
                         <f:selectItems value="#{sessionBean.languages}" var="language" itemLabel="#{language.name}" itemValue="#{language.id}"/>
                    </rich:select>
                    <br/><br/>
                    <h:selectBooleanCheckbox id="showTranslated" value="#{sessionBean.showTranslated}">
                        <a4j:ajax execute="@this" event="change"
                                listener="#{sessionBean.onShowTranslatedChanged}" render="@form"/> 
                    </h:selectBooleanCheckbox>
                    <h:outputText value=" Show already translated strings"/>
                    <br/><br/>
                    <h:outputText value="Project: "/>
                    <rich:select id="project" value="#{sessionBean.projectsCurrent}">
                         <a4j:ajax execute="@this" event="selectitem"
                                   listener="#{sessionBean.onProjectSelected}" render="@form"/>
                         <f:selectItems value="#{sessionBean.projects}" var="project" itemLabel="#{project.name}" itemValue="#{project.id}"/>
                    </rich:select>
                    <br/><br/>
                    <rich:extendedDataTable value="#{sessionBean.strings}" var="item"
                                            id="strings" selectionMode="single"
                                            selection="#{sessionBean.stringsCurrent}"
                                            clientRows="50"
                                            style="width:100%; height:320px">
                        <a4j:ajax execute="@this" event="selectionchange"
                                  listener="#{sessionBean.onStringSelected}" render="right"/>
                        <rich:column width="400px">
                            <h:outputText value="#{item.text}" escape="false"/>
                        </rich:column>
                    </rich:extendedDataTable>
                    <br/><br/>
                    <h:inputText style="width:100%" id="stringToAdd" value="#{sessionBean.stringToAdd}"/>
                    <br/>
                    <a4j:commandButton id="addString" value=" Add String "> 
                        <a4j:ajax execute="stringToAdd" event="click"
                                  listener="#{sessionBean.onAddString}" render="@form"/>
                    </a4j:commandButton>
                </rich:panel>
                <rich:panel style="width:400px; height:600px" id="right">
                    <br/>
                    <h:outputText style="font-size: 18px;" value="#{sessionBean.string}" escape="false"/>
                    <br/><br/>
                    <h:outputText value="Translate from: "/>
                    <rich:select id="translateFrom" value="#{sessionBean.translateFromCurrent}">
                         <a4j:ajax execute="@this" event="selectitem"
                                   listener="#{sessionBean.onTranslateFromSelected}" render="source"/>
                         <f:selectItems value="#{sessionBean.languages}" var="language" itemLabel="#{language.name}" itemValue="#{language.id}"/>
                    </rich:select>
                    <br/>
                    <h:inputTextarea disabled="true" id="source" rows="4" value="#{sessionBean.source}">
                    </h:inputTextarea>
                    <br/><br/>
                    <h:outputText value="Translation"/>
                    <br/>
                    <h:inputTextarea id="translation" rows="4" value="#{sessionBean.translation}">
                    </h:inputTextarea>
                    <br/>
                    <a4j:commandButton id="sendTranslation" value=" Send Translation "> 
                        <a4j:ajax execute="translation" event="click"
                                  listener="#{sessionBean.onSendTranslation}" render="right"/>
                    </a4j:commandButton>
                    <br/><br/>
                    <h:outputText value="Tags: "/>
                    <h:inputText id="tags" value="#{sessionBean.tags}"/>
                    <br/>
                    <a4j:commandButton id="updateTags" value=" Update Tags "> 
                        <a4j:ajax execute="tags" event="click"
                                  listener="#{sessionBean.onUpdateTags}" render="tags"/>
                    </a4j:commandButton>
                </rich:panel>
            </h:panelGrid> 
        </h:form>
    </h:body>
</html>